name: Continuous Deployment Production

on:
  push:
    branches:
      - master

env:
  # TODO... Enter your secrets here... 

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Sonar
          uses: ### TODO
        - name: Build
          uses: ### TODO

  deploy-production:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - name: deploy
        uses: ### TODO

