name: Continuous Deployment UAT

on:
  push:
    branches:
      - develop

env:
  ### TODO... Enter your secrets here... 

jobs:
  quality:
    runs-on: ubuntu-latest
    steps: 
      - name: Quality 
        run: echo "TODO" ### TODO


  build: 
    runs-on: ubuntu-latest
    needs: [quality]
    steps: 
      - uses: actions/checkout@v2
      - name: Build
        run: echo "TODO!" ### TODO


  deploy-production:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - name: deploy
        run: echo "TODO!" ### TODO